server:
  port: 8761
  tomcat:
       uri-encoding: UTF-8 # character encoding to use for URL decoding
spring:
  profiles:
    active: dev
  application:
     name: eureka

---
spring:
   profiles:  dev
eureka:
  instance:
    hostname: eureka.justdj.top
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://122.152.193.63:8761/eureka
  server:
    enable-self-preservation: false
#  server:
#    enableSelfPreservation: false
---
spring:
   profiles:  test
eureka:
  instance:
    hostname: 122.152.193.63
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://122.152.193.63:8761/eureka
  server:
    enable-self-preservation: false
#  server:
#    enableSelfPreservation: false
---
spring:
   profiles:  online
eureka:
  instance:
    hostname: 122.152.193.63
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://122.152.193.63:8761/eureka
  server:
    enable-self-preservation: false


