server:
  port: 8761
  tomcat:
       uri-encoding: UTF-8 # character encoding to use for URL decoding
spring:
  profiles:
    active: dev
  application:
     name: eureka

---
spring:
   profiles:  dev
eureka:
  instance:
    hostname: eureka.justdj.top
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
#  server:
#    enableSelfPreservation: false
---
spring:
   profiles:  test
eureka:
  instance:
    hostname: 172.16.46.224
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
#  server:
#    enableSelfPreservation: false
---
spring:
   profiles:  online
eureka:
  instance:
    hostname: 172.16.46.225
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false


